### ISSUE TITLE
Add option to use channel logos provided by XMLTV

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.vbox#60]
Mentioned in #59

**Comment by sunstealer** [comment]
I expect you already know but just in case you don't, here is the link to the .cpp code for the simple IPTV client - the XMLTV parsing in this add on works perfectly.  Rather than reinventing the wheel, why not repurpose some existing code?  Or if not, perhaps it is helpful to see what they did.

https://github.com/afedchin/xbmc-addon-iptvsimple/blob/master/src/iptvsimple/PVRIptvData.cpp

**Comment by Jalle19** [comment]
I'm trying to make this addon's XMLTV code separate from the rest of the addon so others can reuse it. It uses a different XML parsing library than most other addons so the code is not easily portable.

**Comment by sunstealer** [comment]
ok - I look forward to its development - a combination of Simple IPTV's EPG with the recording abilities supported by your plugin should make the vbox an ideal backend for a versatile PVR in Kodi
