### ISSUE TITLE
Support repeating timers

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.vbox#88]
The new PVR API provides a way for addons to specify what kind of timer types it supports. The VBox SDK supports two types of repeating timers - "standard" ones and CRID-based. The PVR API doesn't support CRID at all (mainly because "no one" uses it) so the first and most important step would be to support the "standard" repeating timers.

The API supports the following "attributes":

One-time time-based (also used when external guide data is used):
- `PVR_TIMER_TYPE_IS_MANUAL`
- `PVR_TIMER_TYPE_IS_READONLY`
- `PVR_TIMER_TYPE_SUPPORTS_CHANNELS`
- `PVR_TIMER_TYPE_SUPPORTS_START_END_TIME`

One-time EPG-based (only usable with internal guide data):
- `PVR_TIMER_TYPE_IS_READONLY`
- `PVR_TIMER_TYPE_SUPPORTS_CHANNELS`
- `PVR_TIMER_TYPE_SUPPORTS_START_END_TIME`

Repeating time-based:
- `PVR_TIMER_TYPE_IS_MANUAL`
- `PVR_TIMER_TYPE_IS_REPEATING`
- `PVR_TIMER_TYPE_IS_READONLY`
- `PVR_TIMER_TYPE_SUPPORTS_CHANNELS`
- `PVR_TIMER_TYPE_SUPPORTS_START_END_TIME`
- `PVR_TIMER_TYPE_SUPPORTS_WEEKDAYS`

As can be seen from the above list, all timers created on the VBox are `PVR_TIMER_TYPE_IS_READONLY` because the SDK doesn't expose methods for editing them.

To make matters more managable, some code restructuring is required. We need to separate the timer and recording representations, which means there will be `m_timers` and `m_recordings`. We'll also need an adapter that can convert between our internal timer represetnations and Kodi's `PVR_TIMER`. We also need a way to turn a `PVR_TIMER` definition into a `request::ApiRequest`.

**Comment by Jalle19** [comment]
@ksooo can you take a quick look at the timer attributes I've described here and tell me if this is how they're supposed to be used? So basically this addon will provide three separate `PVR_TIMER_TYPE` structs to Kodi.

**Comment by ksooo** [comment]
* Repeating-time-based type must include <code>PVR_TIMER_TYPE_IS_MANUAL</code>, otherwise it would denote an EPG-based type.
* One-time EPG-based should include <code>PVR_TIMER_TYPE_SUPPORTS_START_END_TIME</code>, otherwise start and end time will not be displayed (read-only in your case) in the timer settings dialog.

**Comment by Jalle19** [comment]
Thanks for the feedback, I updated the original post

**Comment by ksooo** [comment]
BTW, having only read-only timers should work, but it would be great if you could do some extra testing for functionality that tries to create / edit timers, like context menu entries (which should not be available, then). I did my best to respect all this, but possibly there are still some bugs.

**Comment by brubri** [comment]
I am not 100% sure but I want to say that I would also like to have this feature meaning (for me) that I can set a timer that for example records the news at 20:00 every day or the week or Mon-Fri etc...

**Comment by gti11111111** [comment]
Hi, I am looking for this feature as well. More than 1 year passed since the last update on this thread, but is there any news on this? It seems to be part of the add-on, but I receive either an error message in Kodi when I try to set repeatiing timer or the set timer is not repeating, but behaves as one single timer.

I have the following setup:
VBox:
Product Number  3452
Software Version  XTI_VJ.2.54.2

Kodi: Kodi 16.1 "Jarvis"
VBox TV Gateway PVR Client version: 2.1.10

Thanks for support in advance!

**Comment by Jalle19** [comment]
This addon has been on life support for a while. I may have some time to work on it during the Kodi developer conference, but I wouldn't get my hopes up if I were you.

**Comment by relipo** [comment]
@Jalle19 Hey there,
I know it's been a while, but I have an implementation for my own timer types - EPG based, series (manual & auto) etc.
But I don't want to put out a pull request yet, since I have this issue that happens sometimes, when I go to the timers icons (for manual timers): 
For some reason, the more channels I have, the more this happens - the timer types reduce from 2 manual types (one-time & repeating) to one (the repeating one), and when I set that one - it's wrongly identified, and sends out a one-time timer type.

Would you like to look at the code, could that be a known issue on the Kodi side, rather than on the add-on side, or how could we handle this?

Also (related or not), there seems to be a general crashing problem (without my implementation) when there are many channels - while loading the guide.

**Comment by Jalle19** [comment]
Implemented in https://github.com/kodi-pvr/pvr.vbox/pull/144
